#!/usr/bin/env bash


[[ $# -ne 1 ]] && echo "Erro 1: Os parâmetros foram passados incorretamente, use 'ufc [arquivo]'." && exit 1 #Verifica se os parâmetros estão corretos
arquivo=$1
[[ ! -f $arquivo ]] && echo "Erro 2: O arquivo especificado não existe." && exit 2 #Verifica se o arquivo especificado existe
ext=${arquivo##*.} #Retira a extensão do arquivo e a armazena em uma variável
case $ext in #Vai executar o compilador correnspondente a cada extensão
	"py")
		python3 -u $arquivo  ;; #Python
	"sh"|$arquivo)
		./$arquivo  ;; #shell script
esac